---
- name: Create Kubernetes Namespace (real, supports kubeconfig/token/cert)
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - kubernetes.core

  vars:
    # ---- 認證模式：kubeconfig | token | certificate ----
    auth_mode: "certificate"

    # 共用設定
    host: ""
    verify_ssl: true
    ns_name: "demo"
    labels: {}
    annotations: {}

    # ========== kubeconfig 模式 ==========
    kubeconfig: "~/.kube/config"
    kubecontext: ""

    # ========== token 模式 ==========
    api_key: ""

    # ========== 憑證模式 ==========
    # ⚠️ 從外部變數帶入（AWX extra_vars）
    ca_data: ""
    client_certificate_data: ""
    client_key_data: ""

  tasks:
    - name: Show effective variables (redacted)
      ansible.builtin.debug:
        msg:
          auth_mode: "{{ auth_mode }}"
          host: "{{ host }}"
          verify_ssl: "{{ verify_ssl }}"
          ns_name: "{{ ns_name }}"
          labels: "{{ labels }}"
          annotations: "{{ annotations }}"

    - name: Basic param checks
      ansible.builtin.assert:
        that:
          - ns_name | length > 0
          - auth_mode in ['kubeconfig','token','certificate']
          - (auth_mode != 'kubeconfig') or (kubeconfig | length > 0)
          - (auth_mode != 'token') or (api_key | length > 0 and host | length > 0)
          - (auth_mode != 'certificate') or (host | length > 0 and ca_data | length > 0 and client_certificate_data | length > 0 and client_key_data | length > 0)
        fail_msg: "參數不完整或不合法：請檢查 ns_name / auth_mode 與對應憑證或連線參數。"

    # =========================
    # Certificate 模式（含清理）
    # =========================
    - name: Ensure namespace via client certificate (with temp files & cleanup)
      when: auth_mode == 'certificate'
      block:
        - name: Create temp files for certs
          ansible.builtin.tempfile:
            state: file
            suffix: "{{ item }}"
          loop:
            - "-ca.crt"
            - "-client.crt"
            - "-client.key"
          register: tmp_files

        - name: Set temp paths
          ansible.builtin.set_fact:
            ca_file: "{{ tmp_files.results[0].path }}"
            cert_file: "{{ tmp_files.results[1].path }}"
            key_file: "{{ tmp_files.results[2].path }}"

        - name: Decode and write CA cert
          ansible.builtin.copy:
            dest: "{{ ca_file }}"
            content: >-
              {% set decoded = ca_data | regex_replace('\\s+','') | b64decode %}
              {% if '-----BEGIN' in decoded %}
              {{ decoded }}
              {% else %}
              {{ decoded | b64decode }}
              {% endif %}
            mode: "0600"

        - name: Decode and write client cert
          ansible.builtin.copy:
            dest: "{{ cert_file }}"
            content: >-
              {% set decoded = client_certificate_data | regex_replace('\\s+','') | b64decode %}
              {% if '-----BEGIN' in decoded %}
              {{ decoded }}
              {% else %}
              {{ decoded | b64decode }}
              {% endif %}
            mode: "0600"

        - name: Decode and write client key
          ansible.builtin.copy:
            dest: "{{ key_file }}"
            content: >-
              {% set decoded = client_key_data | regex_replace('\\s+','') | b64decode %}
              {% if '-----BEGIN' in decoded %}
              {{ decoded }}
              {% else %}
              {{ decoded | b64decode }}
              {% endif %}
            mode: "0600"

        - name: Ensure namespace exists (certificate)
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: "{{ ns_name }}"
                labels: "{{ labels | default({}) }}"
                annotations: "{{ annotations | default({}) }}"
            host: "{{ host }}"
            ssl_ca_cert: "{{ ca_file }}"
            cert_file: "{{ cert_file }}"
            key_file: "{{ key_file }}"
            validate_certs: "{{ verify_ssl }}"
          register: ns_result_cert

        - name: Report result (certificate)
          ansible.builtin.debug:
            msg: "Namespace '{{ ns_name }}' ensured (certificate). changed={{ ns_result_cert.changed }}"

      always:
        - name: Remove temp cert files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ ca_file | default('') }}"
            - "{{ cert_file | default('') }}"
            - "{{ key_file | default('') }}"

    # =========================
    # Token 模式
    # =========================
    - name: Ensure namespace via bearer token
      when: auth_mode == 'token'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ ns_name }}"
            labels: "{{ labels | default({}) }}"
            annotations: "{{ annotations | default({}) }}"
        host: "{{ host }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ verify_ssl }}"
      register: ns_result_token

    - name: Report result (token)
      when: auth_mode == 'token'
      ansible.builtin.debug:
        msg: "Namespace '{{ ns_name }}' ensured (token). changed={{ ns_result_token.changed }}"

    # =========================
    # Kubeconfig 模式
    # =========================
    - name: Ensure namespace via kubeconfig
      when: auth_mode == 'kubeconfig'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ ns_name }}"
            labels: "{{ labels | default({}) }}"
            annotations: "{{ annotations | default({}) }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kubecontext if kubecontext | length > 0 else omit }}"
        validate_certs: "{{ verify_ssl }}"
      register: ns_result_kcfg

    - name: Report result (kubeconfig)
      when: auth_mode == 'kubeconfig'
      ansible.builtin.debug:
        msg: "Namespace '{{ ns_name }}' ensured (kubeconfig). changed={{ ns_result_kcfg.changed }}"
