---
- name: 🚀 Kubernetes Project Setup (AWX Final & Corrected Version)
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - kubernetes.core

  vars:
    # ------------------------------------
    # I. 用戶輸入變數 (應由 AWX Extra Variables 提供)
    # ------------------------------------
    ns_name: "demo"
    total_cpu_limit: "10"
    total_memory_limit: "20Gi"
    total_storage_limit: "1TB"
    
    # PVC 專屬設定
    create_default_pvc: true
    default_pvc_size: "50Gi"
    default_storage_class: "microk8s-hostpath" 

    # ------------------------------------
    # II. 靜態配置/預設值
    # ------------------------------------
    request_ratio: 0.8          # Requests 比例：預設 80%
    create_resource_quota: true
    create_limit_range: false
    create_default_deny_network_policy: false
    
    # Metadata (可由外部 JSON 覆寫)
    labels: {}
    annotations: {}


  # 確保 pre_tasks 區塊與 vars 區塊層級相同 (頂層，沒有縮排)
  pre_tasks:
    # 確保任務名稱 (name) 縮排兩個空格
    - name: Pre_1. Calculate Resource Quota Requests and Define Final Objects
      # 確保 set_fact 縮排四個空格
      ansible.builtin.set_fact:
        # 1. 計算 CPU Requests (已修正，確保是整數)
        calculated_cpu_request: "{{ ((total_cpu_limit | int * request_ratio) | round | int) | string }}"
        
        # 2. 計算 Memory Requests
        calculated_memory_request: "{{ (total_memory_limit | regex_replace('Gi', '') | float * request_ratio) | int | string + 'Gi' }}"
        
        # 3. 組合 ResourceQuota Hard 參數
        resource_quota_hard:
          limits.cpu: "{{ total_cpu_limit }}"
          requests.cpu: "{{ calculated_cpu_request }}"
          limits.memory: "{{ total_memory_limit }}"
          requests.memory: "{{ calculated_memory_request }}"
          requests.storage: "{{ total_storage_limit }}"
          persistentvolumeclaims: 50
          
        # 4. 組合 K8s 物件名稱
        default_pvc_name: "{{ ns_name }}-default-pvc"
        resource_quota_name: "{{ ns_name }}-quota"
        limit_range_name: "{{ ns_name }}-limits"


  # 確保 tasks 區塊與 vars 區塊層級相同 (頂層，沒有縮排)
  tasks:
    - name: 0. Show final calculated configuration
      ansible.builtin.debug:
        msg: |
          Project Namespace: {{ ns_name }}
          - CPU Limits/Requests: {{ total_cpu_limit }}/{{ calculated_cpu_request }}
          - Memory Limits/Requests: {{ total_memory_limit }}/{{ calculated_memory_request }}
          - Storage Limit: {{ total_storage_limit }}
          - PVC Name & Size: {{ default_pvc_name }} ({{ default_pvc_size }})

    # =========================
    # 1. Create/Ensure Namespace
    # =========================
    - name: 1. Create/Ensure Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ ns_name }}"
            labels: "{{ labels | default({}) }}"
            annotations: "{{ annotations | default({}) }}"

    # =========================
    # 2. Create/Update ResourceQuota
    # =========================
    - name: 2. Create/Update ResourceQuota
      when: create_resource_quota | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: "{{ resource_quota_name }}"
            namespace: "{{ ns_name }}"
          spec:
            hard: "{{ resource_quota_hard }}"

    # =========================
    # 3. Create/Update LimitRange
    # =========================
    - name: 3. Create/Update LimitRange
      when: create_limit_range | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: LimitRange
          metadata:
            name: "{{ limit_range_name }}"
            namespace: "{{ ns_name }}"
          spec:
            limits:
              - type: Container
                default: {cpu: "500m", memory: "512Mi"}
                defaultRequest: {cpu: "100m", memory: "128Mi"}
                max: {cpu: "2", memory: "2Gi"}
                min: {cpu: "50m", memory: "64Mi"}

    # =========================
    # 4. Create PersistentVolumeClaim
    # =========================
    - name: 4. Create default PVC ({{ default_pvc_name }})
      when: create_default_pvc | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "{{ default_pvc_name }}"
            namespace: "{{ ns_name }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "{{ default_pvc_size }}"
            storageClassName: "{{ default_storage_class if default_storage_class | length > 0 else omit }}"

    # =========================
    # 5. Create Default Deny NetworkPolicy
    # =========================
    - name: 5. Create default deny all ingress/egress NetworkPolicy
      when: create_default_deny_network_policy | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ ns_name }}-default-deny"
            namespace: "{{ ns_name }}"
          spec:
            podSelector: {}
            policyTypes: [Ingress, Egress]

    # ---- 最終總結 ----
    - name: Print Final Result Summary
      ansible.builtin.debug:
        msg: "✅ Namespace '{{ ns_name }}' setup complete. Quota Requests: CPU {{ calculated_cpu_request }}, Memory {{ calculated_memory_request }}."
