# Step 1: Create VPC / Subnets / Security Groups / Route Tables / SSH Key (+ NAT)

- name: Step 1 - Create VPC, Subnets, Security Groups, Endpoints
  hosts: localhost
  gather_facts: true
  collections:
    - amazon.aws

  vars:
    # ─────────────────────────────────────────────
    # Region (wrapper pattern, safe)
    # ─────────────────────────────────────────────
    default_cluster_region: ap-northeast-1
    cluster_region_input: "{{ cluster_region | default(omit) }}"
    cluster_region: "{{ cluster_region_input | default(default_cluster_region) }}"
    default_az: "{{ cluster_region }}a"

    enable_external_ssh: true
    office_ip: "0.0.0.0/0"

    # ─────────────────────────────────────────────
    # NAT feature flag (wrapper pattern, safe)
    # ─────────────────────────────────────────────
    default_enable_nat_gateway: false
    enable_nat_gateway_effective: "{{ enable_nat_gateway | default(default_enable_nat_gateway) }}"

    # ─────────────────────────────────────────────
    # Endpoints feature flags
    # ─────────────────────────────────────────────
    enable_ssm_endpoints: false   # 若你不用 SSM，可設 false

  tasks:

    # ─────────────────────────────────────────────
    # VPC
    # ─────────────────────────────────────────────
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}"
        cidr_block: "{{ vpc_cidr }}"
        state: present
        tags:
          Name: "{{ project_name }}"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ProjectId: "{{ project_labels['project.id'] }}"
          ManagedBy: Ansible
      register: vpc_result

    - set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"

    # ※ 確保 VPC DNS 功能正常（Private DNS / VPCE 依賴）
    - name: Ensure VPC DNS support/hostnames enabled
      amazon.aws.ec2_vpc_net:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        enable_dns_support: true
        enable_dns_hostnames: true
      register: vpc_dns_result

    # ─────────────────────────────────────────────
    # IGW
    # ─────────────────────────────────────────────
    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-igw"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      when: subnets | selectattr('is_public','equalto',true) | list | length > 0
      register: igw_result

    - set_fact:
        igw_id: "{{ igw_result.gateway_id }}"
      when: igw_result.gateway_id is defined

    # ─────────────────────────────────────────────
    # Subnets
    # ─────────────────────────────────────────────
    - name: Create Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az | default(default_az) }}"
        map_public: "{{ item.is_public }}"
        state: present
        tags:
          Name: "{{ item.name }}"
          Project: "{{ project_name }}"
          SubnetName: "{{ item.name }}"
          Purpose: "{{ item.purpose }}"
          Type: "{{ 'Public' if item.is_public else 'Private' }}"
          Env: "{{ project_labels.env }}"
      loop: "{{ subnets }}"
      register: subnet_results

    - set_fact:
        public_subnet_ids: "{{ subnet_results.results
          | selectattr('subnet.map_public_ip_on_launch','equalto',true)
          | map(attribute='subnet.id') | list }}"

    - set_fact:
        private_subnet_ids: "{{ subnet_results.results
          | selectattr('subnet.map_public_ip_on_launch','equalto',false)
          | map(attribute='subnet.id') | list }}"

    # ─────────────────────────────────────────────
    # Route Tables
    # ─────────────────────────────────────────────
    - name: Create public route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ public_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-rt-public"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_id }}"
      when:
        - public_subnet_ids | length > 0
        - igw_id is defined

    - name: Create private route table (empty by default)
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-rt-private"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        routes: []
      when: private_subnet_ids | length > 0

    # ─────────────────────────────────────────────
    # NAT Gateway (optional)
    # ─────────────────────────────────────────────
    - name: Lookup existing NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ cluster_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          state: available
          tag:Name: "{{ project_name }}-nat-gw"
      register: existing_nat
      when:
        - enable_nat_gateway_effective
        - private_subnet_ids | length > 0

    - name: Use existing NAT Gateway if found
      set_fact:
        nat_gateway_id: "{{ existing_nat.result[0].nat_gateway_id }}"
      when:
        - enable_nat_gateway_effective
        - existing_nat.result | default([]) | length > 0

    - name: Select public subnet for NAT Gateway
      set_fact:
        nat_public_subnet_id: "{{ public_subnet_ids[0] }}"
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is not defined
        - public_subnet_ids | length > 0

    - name: Allocate Elastic IP for NAT Gateway
      amazon.aws.ec2_eip:
        region: "{{ cluster_region }}"
        in_vpc: true
        state: present
        tags:
          Name: "{{ project_name }}-nat-eip"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      register: nat_eip
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is not defined

    - name: Create NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway:
        region: "{{ cluster_region }}"
        subnet_id: "{{ nat_public_subnet_id }}"
        allocation_id: "{{ nat_eip.allocation_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-nat-gw"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      register: nat_gw
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is not defined

    - set_fact:
        nat_gateway_id: "{{ nat_gw.nat_gateway_id }}"
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is not defined

    - name: Wait for NAT Gateway to become available
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ cluster_region }}"
        nat_gateway_ids:
          - "{{ nat_gateway_id }}"
      register: nat_gw_info
      until: nat_gw_info.result[0].state == "available"
      retries: 15
      delay: 20
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is defined

    - name: Attach NAT Gateway to private route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-rt-private"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ nat_gateway_id }}"
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is defined

    # ─────────────────────────────────────────────
    # Security Groups
    # 1) 給 EC2 用的共用 SG（Endpoint SG 將以此為來源）
    # 2) 保留你原本每 subnet 的 SG（如果你後續還會用）
    # ─────────────────────────────────────────────
    - name: Create common EC2 Security Group
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-ec2-sg"
        description: "Common SG for EC2 instances in {{ project_name }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-ec2-sg"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        rules:
          # 允許 VPC 內互通（你可依需求縮小）
          - proto: all
            cidr_ip: "{{ vpc_cidr }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: ec2_common_sg

    - set_fact:
        ec2_common_sg_id: "{{ ec2_common_sg.group_id }}"

    - name: Create Security Groups for each subnet (optional / keep legacy)
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ item.name | regex_replace('-subnet$', '-sg') }}"
        description: "Security Group for {{ item.name }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ item.name | regex_replace('-subnet$', '-sg') }}"
          Project: "{{ project_name }}"
          SubnetName: "{{ item.name }}"
          Env: "{{ project_labels.env }}"
        rules:
          - proto: all
            cidr_ip: "{{ vpc_cidr }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      loop: "{{ subnets }}"

    # ─────────────────────────────────────────────
    # Key Pair
    # ─────────────────────────────────────────────
    - name: Create key pair
      amazon.aws.ec2_key:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-keypair"
        state: present
        tags:
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ManagedBy: Ansible
      register: keypair_result

    - name: Expose SSH private key to frontend (FIRST TIME ONLY)
      set_stats:
        data:
          ssh_private_key_pem: "{{ keypair_result.key.private_key }}"
          ssh_keypair_name: "{{ keypair_result.key.name }}"
      when:
        - keypair_result.changed
        - keypair_result.key.private_key is defined

    # ─────────────────────────────────────────────
    # VPC Interface Endpoints for CloudWatch / STS (+ optional SSM)
    # 重要改動：
    # 1) Endpoint SG 入站來源改成 EC2 SG（不要用 CIDR）
    # 2) 加上 STS endpoint（private subnet 沒 NAT 時必備）
    # ─────────────────────────────────────────────
    - name: Create VPC Endpoint Security Group
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-vpce-sg"
        description: "SG for VPC Interface Endpoints"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-vpce-sg"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            group_id: "{{ ec2_common_sg_id }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: vpce_sg
      when: private_subnet_ids | length > 0

    - name: Create CloudWatch Metrics Endpoint
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.monitoring"
        vpc_endpoint_type: Interface
        state: present
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
      when: private_subnet_ids | length > 0

    - name: Create CloudWatch Logs Endpoint
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.logs"
        vpc_endpoint_type: Interface
        state: present
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
      when: private_subnet_ids | length > 0

    # ✅ 關鍵：STS endpoint（沒有 NAT 時，CloudWatch Agent / SDK 常會卡在取憑證）
    - name: Create STS Endpoint (required for private subnet without NAT)
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.sts"
        vpc_endpoint_type: Interface
        state: present
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
      when: private_subnet_ids | length > 0

    # 你原本有 EC2 API endpoint：保留（有些情境 agent / tooling 會用到）
    - name: Create EC2 API Endpoint
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.ec2"
        vpc_endpoint_type: Interface
        state: present
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
      when: private_subnet_ids | length > 0

    # （可選）若你用 SSM/Session Manager/Parameter Store 裝 agent 或管機器，建議加
    - name: Create SSM Endpoint
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.ssm"
        vpc_endpoint_type: Interface
        state: present
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
      when:
        - private_subnet_ids | length > 0
        - enable_ssm_endpoints | bool

    - name: Create SSM Messages Endpoint
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.ssmmessages"
        vpc_endpoint_type: Interface
        state: present
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
      when:
        - private_subnet_ids | length > 0
        - enable_ssm_endpoints | bool

    - name: Create EC2 Messages Endpoint
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.ec2messages"
        vpc_endpoint_type: Interface
        state: present
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
      when:
        - private_subnet_ids | length > 0
        - enable_ssm_endpoints | bool

    # ─────────────────────────────────────────────
    # Summary
    # ─────────────────────────────────────────────
    - name: Summary
      debug:
        msg:
          - "VPC ID: {{ vpc_id }}"
          - "Public Subnets: {{ public_subnet_ids }}"
          - "Private Subnets: {{ private_subnet_ids }}"
          - "EC2 Common SG: {{ ec2_common_sg_id }}"
          - "NAT Enabled: {{ enable_nat_gateway_effective }}"
          - "NAT Gateway: {{ nat_gateway_id | default('N/A') }}"
          - "SSM Endpoints Enabled: {{ enable_ssm_endpoints }}"

