- name: Step 1 - Create VPC, Subnets, Route Tables, NAT, SG, Endpoints
  hosts: localhost
  gather_facts: true
  collections:
    - amazon.aws

  vars:
    # ─────────────────────────────────────────────
    # Region
    # ─────────────────────────────────────────────
    default_cluster_region: ap-northeast-1
    cluster_region: "{{ cluster_region | default(default_cluster_region) }}"
    default_az: "{{ cluster_region }}a"

    # ─────────────────────────────────────────────
    # SSH control
    # ─────────────────────────────────────────────
    enable_external_ssh: true
    office_ip: "0.0.0.0/0"

    # ─────────────────────────────────────────────
    # Feature flags
    # ─────────────────────────────────────────────
    default_enable_nat_gateway: false
    enable_nat_gateway_effective: >-
      {{ enable_nat_gateway
         | default(default_enable_nat_gateway)
         | bool }}

    default_enable_ssm_endpoints: false
    enable_ssm_endpoints_effective: >-
      {{ enable_ssm_endpoints
         | default(default_enable_ssm_endpoints)
         | bool }}

    default_enable_cloudwatch_endpoints: true
    enable_cloudwatch_endpoints_effective: >-
      {{ enable_cloudwatch_endpoints
         | default(default_enable_cloudwatch_endpoints)
         | bool }}

  tasks:

    # ─────────────────────────────────────────────
    # Validate subnet definitions
    # ─────────────────────────────────────────────
    - name: Validate subnet definitions
      assert:
        that:
          - item.name is defined
          - item.cidr is defined
          - item.is_public is defined
          - item.is_public in [true, false]
        fail_msg: "Subnet {{ item.name | default('UNKNOWN') }} must define name, cidr, is_public"
      loop: "{{ subnets }}"

    # ─────────────────────────────────────────────
    # VPC
    # ─────────────────────────────────────────────
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}"
        cidr_block: "{{ vpc_cidr }}"
        state: present
        dns_support: true
        dns_hostnames: true
        tags:
          Name: "{{ project_name }}"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ProjectId: "{{ project_labels['project.id'] }}"
          ManagedBy: Ansible
      register: vpc_result

    - set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"

    # ─────────────────────────────────────────────
    # Internet Gateway
    # ─────────────────────────────────────────────
    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-igw"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      when: subnets | selectattr('is_public','equalto',true) | length > 0
      register: igw_result

    - set_fact:
        igw_id: "{{ igw_result.gateway_id }}"
      when: igw_result.gateway_id is defined

    # ─────────────────────────────────────────────
    # Subnets
    # ─────────────────────────────────────────────
    - name: Create Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az | default(default_az) }}"
        map_public: "{{ item.is_public }}"
        state: present
        tags:
          Name: "{{ item.name }}"
          Project: "{{ project_name }}"
          SubnetName: "{{ item.name }}"
          Type: "{{ 'Public' if item.is_public else 'Private' }}"
          Env: "{{ project_labels.env }}"
      loop: "{{ subnets }}"
      register: subnet_results

    - set_fact:
        public_subnet_ids: "{{ subnet_results.results
          | selectattr('subnet.map_public_ip_on_launch','equalto',true)
          | map(attribute='subnet.id') | list }}"

    - set_fact:
        private_subnet_ids: "{{ subnet_results.results
          | selectattr('subnet.map_public_ip_on_launch','equalto',false)
          | map(attribute='subnet.id') | list }}"

    # ─────────────────────────────────────────────
    # Validate NAT prerequisites
    # ─────────────────────────────────────────────
    - name: Validate NAT prerequisites
      assert:
        that:
          - public_subnet_ids | length > 0
        fail_msg: "enable_nat_gateway=true requires at least one public subnet"
      when: enable_nat_gateway_effective

    # ─────────────────────────────────────────────
    # Route Tables
    # ─────────────────────────────────────────────
    - name: Create public route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ public_subnet_ids }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_id }}"
        tags:
          Name: "{{ project_name }}-rt-public"
          Project: "{{ project_name }}"
      when:
        - public_subnet_ids | length > 0
        - igw_id is defined

    - name: Create private route table (empty by default)
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        routes: []
        tags:
          Name: "{{ project_name }}-rt-private"
          Project: "{{ project_name }}"
      register: private_rt        
      when: private_subnet_ids | length > 0

    # ─────────────────────────────────────────────
    # NAT Gateway
    # ─────────────────────────────────────────────
    - name: Lookup existing NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ cluster_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          state: available
          tag:Name: "{{ project_name }}-nat-gw"
      register: existing_nat
      when:
        - enable_nat_gateway_effective
        - private_subnet_ids | length > 0

    - set_fact:
        nat_gateway_id: "{{ existing_nat.result[0].nat_gateway_id }}"
      when:
        - enable_nat_gateway_effective
        - existing_nat.result | length > 0

    - name: Allocate EIP for NAT
      amazon.aws.ec2_eip:
        region: "{{ cluster_region }}"
        in_vpc: true
        state: present
      register: nat_eip
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is not defined

    - name: Create NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway:
        region: "{{ cluster_region }}"
        subnet_id: "{{ public_subnet_ids[0] }}"
        allocation_id: "{{ nat_eip.allocation_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-nat-gw"
      register: nat_gw
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is not defined
        - public_subnet_ids | length > 0

    - set_fact:
        nat_gateway_id: "{{ nat_gw.nat_gateway_id }}"
      when:
        - enable_nat_gateway_effective
        - nat_gw.nat_gateway_id is defined

    # ─────────────────────────────────────────────
    # Attach NAT to private route table
    # ─────────────────────────────────────────────
    - name: Attach NAT Gateway to private route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ nat_gateway_id }}"
        tags:
          Name: "{{ project_name }}-rt-private"
          Project: "{{ project_name }}"
      when:
        - enable_nat_gateway_effective
        - nat_gateway_id is defined
        - private_subnet_ids | length > 0

    # ─────────────────────────────────────────────
    # Security Groups
    # ─────────────────────────────────────────────
    - name: Build SG ingress rules
      set_fact:
        sg_ingress_rules: >
          {{ [{'proto':'all','cidr_ip':vpc_cidr}]
             + ([{'proto':'tcp','from_port':22,'to_port':22,'cidr_ip':office_ip}]
                if enable_external_ssh else []) }}

    - name: Create subnet security groups
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ item.name | regex_replace('-subnet$','-sg') }}"
        description: "Security group for subnet {{ item.name }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        rules: "{{ sg_ingress_rules }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        tags:
          Name: "{{ item.name | regex_replace('-subnet$','-sg') }}"
          Project: "{{ project_name }}"
      loop: "{{ subnets }}"

    # ─────────────────────────────────────────────
    # S3 Gateway Endpoint (only when NAT is disabled)
    # ─────────────────────────────────────────────
    - name: Create S3 Gateway Endpoint
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.s3"
        vpc_endpoint_type: Gateway
        route_table_ids:
          - "{{ private_rt.route_table.id }}"
        state: present
        tags:
          Name: "{{ project_name }}-vpce-s3"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ManagedBy: Ansible
      when:
        - private_subnet_ids | length > 0
        - not enable_nat_gateway_effective

    # ─────────────────────────────────────────────
    # VPC Endpoints
    # ─────────────────────────────────────────────
    - name: Create VPC Endpoint SG
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-vpce-sg"
        description: "Security group for VPC interface endpoints"
        vpc_id: "{{ vpc_id }}"
        state: present
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "{{ vpc_cidr }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        tags:
          Name: "{{ project_name }}-vpce-sg"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ManagedBy: Ansible
      register: vpce_sg
      when:
        - private_subnet_ids | length > 0
        - enable_cloudwatch_endpoints_effective
          or enable_ssm_endpoints_effective

    - name: Create CloudWatch / STS Endpoints
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.{{ item }}"
        vpc_endpoint_type: Interface
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-vpce-{{ item }}"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ManagedBy: Ansible
      loop: [monitoring, logs, sts]
      when:
        - enable_cloudwatch_endpoints_effective
        - private_subnet_ids | length > 0

    - name: Create SSM Endpoints
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.{{ item }}"
        vpc_endpoint_type: Interface
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ vpce_sg.group_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-vpce-{{ item }}"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ManagedBy: Ansible
      loop: [ssm, ec2messages, ssmmessages]
      when:
        - enable_ssm_endpoints_effective
        - private_subnet_ids | length > 0

    # ─────────────────────────────────────────────
    # Key Pair
    # ─────────────────────────────────────────────
    - name: Create key pair
      amazon.aws.ec2_key:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-keypair"
        state: present
        tags:
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ManagedBy: Ansible
      register: keypair_result

    - name: Expose SSH private key to frontend (FIRST TIME ONLY)
      set_stats:
        data:
          ssh_private_key_pem: "{{ keypair_result.key.private_key }}"
          ssh_keypair_name: "{{ keypair_result.key.name }}"
      when:
        - keypair_result.changed
        - keypair_result.key.private_key is defined

    # ─────────────────────────────────────────────
    # Summary
    # ─────────────────────────────────────────────
    - name: Summary
      debug:
        msg:
          - "VPC ID: {{ vpc_id }}"
          - "Public Subnets: {{ public_subnet_ids }}"
          - "Private Subnets: {{ private_subnet_ids }}"
          - "NAT Enabled (effective): {{ enable_nat_gateway_effective }}"
          - "NAT Gateway: {{ nat_gateway_id | default('N/A') }}"
          - "CloudWatch Endpoints Enabled: {{ enable_cloudwatch_endpoints_effective }}"
          - "SSM Endpoints Enabled: {{ enable_ssm_endpoints_effective }}"


