---
- name: 🚀 Kubernetes Project Setup (AWX Credential Optimized + PVC)
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - kubernetes.core

  vars:
    # ------------------------------------
    # Namespace Configuration
    # ------------------------------------
    ns_name: "demo"
    labels: {}
    annotations: {}

    # ------------------------------------
    # 可選: ResourceQuota (包含 Storage 總量限制)
    # ------------------------------------
    create_resource_quota: false
    resource_quota_name: "rq-default"
    resource_quota_hard: {}  # 例：{"requests.storage":"500Gi"}

    # ------------------------------------
    # 可選: LimitRange (單個容器的資源限制)
    # ------------------------------------
    create_limit_range: false
    limit_range_name: "limits-default"
    limit_range_container_defaults:
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "2"
        memory: "2Gi"
      min:
        cpu: "50m"
        memory: "64Mi"

    # ------------------------------------
    # 新增: PersistentVolumeClaim (預設儲存空間)
    # ------------------------------------
    create_default_pvc: false
    default_pvc_name: "pvc-default-storage"
    default_pvc_size: "10Gi"
    default_storage_class: "microk8s-hostpath" # 請根據您的 MicroK8s 配置調整

    # ------------------------------------
    # 可選: Default Deny NetworkPolicy
    # ------------------------------------
    create_default_deny_network_policy: false
    default_deny_network_policy_name: "np-default-deny"

  tasks:
    - name: Assert required params
      ansible.builtin.assert:
        that:
          - ns_name | length > 0
        fail_msg: "參數缺失：請檢查 ns_name 變數。"

    # =========================
    # 1. Create/Ensure Namespace
    # =========================
    - name: 1. Create/Ensure Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ ns_name }}"
            labels: "{{ labels | default({}) }}"
            annotations: "{{ annotations | default({}) }}"
      register: ns_result

    # =========================
    # 2. Optional: ResourceQuota
    # =========================
    - name: 2. Create/Update ResourceQuota
      when: create_resource_quota | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: "{{ resource_quota_name }}"
            namespace: "{{ ns_name }}"
          spec:
            hard: "{{ resource_quota_hard }}"

    # =========================
    # 3. Optional: LimitRange
    # =========================
    - name: 3. Create/Update LimitRange
      when: create_limit_range | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: LimitRange
          metadata:
            name: "{{ limit_range_name }}"
            namespace: "{{ ns_name }}"
          spec:
            limits:
              - type: Container
                default: "{{ limit_range_container_defaults.default }}"
                defaultRequest: "{{ limit_range_container_defaults.defaultRequest }}"
                max: "{{ limit_range_container_defaults.max }}"
                min: "{{ limit_range_container_defaults.min }}"

    # =========================
    # 4. 新增: PersistentVolumeClaim (PVC)
    # =========================
    - name: 4. Create default PVC for the namespace
      when: create_default_pvc | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "{{ ns_name }}-default-pvc"
            namespace: "{{ ns_name }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "{{ default_pvc_size }}"
            storageClassName: "{{ default_storage_class if default_storage_class | length > 0 else omit }}"
      register: pvc_result

    - name: Report default PVC creation status
      when: create_default_pvc | bool
      ansible.builtin.debug:
        msg: "Default PVC '{{ default_pvc_name }}' ({{ default_pvc_size }}) ensured. Changed: {{ pvc_result.changed }}"

    # =========================
    # 5. Optional: Default Deny NetworkPolicy
    # =========================
    - name: 5. Create default deny all ingress/egress NetworkPolicy
      when: create_default_deny_network_policy | bool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: "{{ default_deny_network_policy_name }}"
            namespace: "{{ ns_name }}"
          spec:
            podSelector: {}
            policyTypes: [Ingress, Egress]

    # ---- 回傳結果 ----
    - name: Print Final Result Summary
      ansible.builtin.debug:
        msg: |
          Project Setup Completed for Namespace: {{ ns_name }}
          - ResourceQuota Applied: {{ create_resource_quota | bool }}
          - LimitRange Applied: {{ create_limit_range | bool }}
          - Default PVC Created: {{ create_default_pvc | bool }}
          - Default Deny Policy: {{ create_default_deny_network_policy | bool }}
