---
# ════════════════════════════════════════════════════════════════
# Step 2: 在指定的 Subnet 建立 EC2 實例
# ════════════════════════════════════════════════════════════════
# 使用場景: Step 1 建立完基礎設施後，使用此腳本建立 EC2
# 
# 前置條件:
#   1. Step 1 已執行完成
#   2. 已有 {project_name}_infrastructure.yml 檔案
#   3. 已知要部署在哪個 Subnet
# ════════════════════════════════════════════════════════════════

- name: Step 2 - Create EC2 Instances in Specified Subnet
  hosts: localhost
  gather_facts: false

  vars:
    default_cluster_region: ap-northeast-1
    cluster_region: "{{ cluster_region | default(default_cluster_region) }}"
    default_key_name: "{{ project_name }}-keypair"
    iam_instance_profile_name: EC2-CloudWatchAgent-Role

  tasks:
    # ─────────────────────────────────────────────
    # 查 VPC
    # ─────────────────────────────────────────────
    - name: Get VPC by name
      amazon.aws.ec2_vpc_net_info:
        region: "{{ cluster_region }}"
        filters:
          "tag:Name": "{{ project_name }}"
      register: vpc_info

    - name: Fail if VPC not found
      fail:
        msg: "VPC {{ project_name }} not found"
      when: vpc_info.vpcs | length == 0

    - set_fact:
        vpc_id: "{{ vpc_info.vpcs[0].id }}"

    # ─────────────────────────────────────────────
    # Subnet map
    # ─────────────────────────────────────────────
    - name: Get subnets
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ cluster_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: subnets_info

    - name: Build subnet map
      set_fact:
        subnet_map: "{{ subnet_map | default({}) | combine({item.tags.Name: item.id}) }}"
      loop: "{{ subnets_info.subnets }}"
      when: item.tags.Name is defined

    # ─────────────────────────────────────────────
    # SG map
    # ─────────────────────────────────────────────
    - name: Get security groups
      amazon.aws.ec2_security_group_info:
        region: "{{ cluster_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: sg_info

    - name: Build SG map
      set_fact:
        sg_map: "{{ sg_map | default({}) | combine({item.tags.Name: item.group_id}) }}"
      loop: "{{ sg_info.security_groups }}"
      when: item.tags.Name is defined

    # ─────────────────────────────────────────────
    # 建 EC2（一台一圈，關鍵在這）
    # ─────────────────────────────────────────────
    - name: Create EC2 instances
      loop: "{{ ec2_instances }}"
      loop_control:
        loop_var: item
      block:

        # 1️⃣ 查 AMI（方法一，正確用法）
        - name: Get AMI info
          amazon.aws.ec2_ami_info:
            region: "{{ cluster_region }}"
            image_ids:
              - "{{ item.ami_id }}"
          register: ami_info

        # 2️⃣ 組 volumes（只有在有 volume_size 時）
        - name: Build volumes config
          set_fact:
            ec2_volumes: >-
              {{ [{
                   'device_name': ami_info.images[0].root_device_name,
                   'ebs': {
                     'volume_size': item.volume_size,
                     'volume_type': 'gp3',
                     'delete_on_termination': true
                   }
                 }] if item.volume_size is defined else omit }}

        # 3️⃣ 建 EC2
        - name: Launch EC2
          amazon.aws.ec2_instance:
            region: "{{ cluster_region }}"
            name: "{{ project_name }}-{{ item.name }}"
            image_id: "{{ item.ami_id }}"
            instance_type: "{{ item.instance_type }}"
            key_name: "{{ item.key_name | default(default_key_name) }}"
            vpc_subnet_id: "{{ subnet_map[item.subnet_name] }}"
            security_groups:
              - "{{ sg_map[item.subnet_name | regex_replace('-subnet$', '-sg')] }}"
            network_interfaces:
              - assign_public_ip: "{{ item.assign_public_ip }}"
                private_ip_address: "{{ item.private_ip }}"
                device_index: 0
            iam_instance_profile: "{{ iam_instance_profile_name }}"
            user_data: "{{ lookup('template', 'templates/cloudwatch_agent_userdata.sh.j2') }}"
            volumes: "{{ ec2_volumes }}"
            tags: "{{ {'Name': project_name ~ '-' ~ item.name} | combine(item.tags | default({})) }}"
            state: running
            wait: yes
