---
- name: Create Kubernetes Namespace (real, supports kubeconfig/token/cert)
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - kubernetes.core

  vars:
    # ---- 選擇認證模式：kubeconfig | token | certificate ----
    auth_mode: "certificate"

    # 共用
    host: ""           # 例如：https://172.26.196.25:16443
    verify_ssl: true   # 有 CA 建議 true；自簽測試且未提供 CA 可暫時 false
    namespace: "demo"
    labels: {}
    annotations: {}

    # ========== kubeconfig 模式 ==========
    kubeconfig: "~/.kube/config"
    kubecontext: ""

    # ========== Bearer Token 模式 ==========
    api_key: ""        # 例如：Bearer xxx.yyy.zzz（請包含 "Bearer " 字首）

    # ========== Client Certificate 模式 ==========
    # 以下三者可直接貼 Base64（含 BEGIN/END 的 PEM 經過 b64），任務中會 b64decode 成檔案
    ca_cert_b64: ""        # CA CERTIFICATE (base64)
    client_cert_b64: ""    # Client CERTIFICATE (base64)
    client_key_b64: ""     # Client PRIVATE KEY (base64)

  tasks:
    - name: Show effective variables (redacted)
      ansible.builtin.debug:
        msg:
          auth_mode: "{{ auth_mode }}"
          host: "{{ host }}"
          verify_ssl: "{{ verify_ssl }}"
          namespace: "{{ namespace }}"
          labels: "{{ labels }}"
          annotations: "{{ annotations }}"

    - name: Basic param checks
      ansible.builtin.assert:
        that:
          - namespace | length > 0
          - auth_mode in ['kubeconfig','token','certificate']
          - (auth_mode != 'kubeconfig') or (kubeconfig | length > 0)
          - (auth_mode != 'token') or (api_key | length > 0 and host | length > 0)
          - (auth_mode != 'certificate') or (host | length > 0 and ca_cert_b64 | length > 0 and client_cert_b64 | length > 0 and client_key_b64 | length > 0)
        fail_msg: "參數不完整或不合法：請檢查 namespace / auth_mode 與對應憑證或連線參數。"

    # =========================
    # Certificate 模式（含清理）
    # =========================
    - name: Ensure namespace via client certificate (with temp files & cleanup)
      when: auth_mode == 'certificate'
      block:
        - name: Create temp file for CA cert
          ansible.builtin.tempfile:
            state: file
            suffix: "-ca.crt"
          register: ca_tmp

        - name: Create temp file for client cert
          ansible.builtin.tempfile:
            state: file
            suffix: "-client.crt"
          register: cert_tmp

        - name: Create temp file for client key
          ansible.builtin.tempfile:
            state: file
            suffix: "-client.key"
          register: key_tmp

        - name: Write CA cert (b64 -> file)
          ansible.builtin.copy:
            dest: "{{ ca_tmp.path }}"
            content: "{{ ca_cert_b64 | b64decode }}"
            mode: "0600"

        - name: Write client cert (b64 -> file)
          ansible.builtin.copy:
            dest: "{{ cert_tmp.path }}"
            content: "{{ client_cert_b64 | b64decode }}"
            mode: "0600"

        - name: Write client key (b64 -> file)
          ansible.builtin.copy:
            dest: "{{ key_tmp.path }}"
            content: "{{ client_key_b64 | b64decode }}"
            mode: "0600"

        - name: Ensure namespace exists (certificate)
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: "{{ namespace }}"
                labels: "{{ labels | default({}) }}"
                annotations: "{{ annotations | default({}) }}"
            host: "{{ host }}"
            ssl_ca_cert: "{{ ca_tmp.path }}"
            cert_file:   "{{ cert_tmp.path }}"
            key_file:    "{{ key_tmp.path }}"
            validate_certs: "{{ verify_ssl }}"
          register: ns_result_cert

        - name: Report result (certificate)
          ansible.builtin.debug:
            msg: "Namespace '{{ namespace }}' ensured (certificate). changed={{ ns_result_cert.changed }}"
      always:
        - name: Remove temp cert files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ ca_tmp.path | default('') }}"
            - "{{ cert_tmp.path | default('') }}"
            - "{{ key_tmp.path | default('') }}"

    # =========================
    # Token 模式
    # =========================
    - name: Ensure namespace via bearer token
      when: auth_mode == 'token'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"
            labels: "{{ labels | default({}) }}"
            annotations: "{{ annotations | default({}) }}"
        host: "{{ host }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ verify_ssl }}"
      register: ns_result_token

    - name: Report result (token)
      when: auth_mode == 'token'
      ansible.builtin.debug:
        msg: "Namespace '{{ namespace }}' ensured (token). changed={{ ns_result_token.changed }}"

    # =========================
    # Kubeconfig 模式
    # =========================
    - name: Ensure namespace via kubeconfig
      when: auth_mode == 'kubeconfig'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"
            labels: "{{ labels | default({}) }}"
            annotations: "{{ annotations | default({}) }}"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ kubecontext if kubecontext | length > 0 else omit }}"
        validate_certs: "{{ verify_ssl }}"
      register: ns_result_kcfg

    - name: Report result (kubeconfig)
      when: auth_mode == 'kubeconfig'
      ansible.builtin.debug:
        msg: "Namespace '{{ namespace }}' ensured (kubeconfig). changed={{ ns_result_kcfg.changed }}"
