# Step 1: Create VPC / Subnets / Security Groups / Route Tables / SSH Key (+ NAT / Endpoints)

- name: Step 1 - Create VPC, Subnets, Security Groups, Endpoints
  hosts: localhost
  gather_facts: true
  collections:
    - amazon.aws

  vars:
    # ─────────────────────────────────────────────
    # Region
    # ─────────────────────────────────────────────
    default_cluster_region: ap-northeast-1
    cluster_region: "{{ cluster_region | default(default_cluster_region) }}"
    default_az: "{{ cluster_region }}a"

    # ─────────────────────────────────────────────
    # SSH control
    # ─────────────────────────────────────────────
    enable_external_ssh: true
    office_ip: "0.0.0.0/0"

    # ─────────────────────────────────────────────
    # Feature flags
    # ─────────────────────────────────────────────
    enable_nat_gateway: false                  # ✅ NAT 預設 false
    enable_cloudwatch_endpoints: false         # ✅ CloudWatch Endpoint 開關
    enable_ssm_endpoints: false                # SSM（可選）

  tasks:

    # ─────────────────────────────────────────────
    # VPC
    # ─────────────────────────────────────────────
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}"
        cidr_block: "{{ vpc_cidr }}"
        state: present
        tags:
          Name: "{{ project_name }}"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ProjectId: "{{ project_labels['project.id'] }}"
          ManagedBy: Ansible
      register: vpc_result

    - set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"

    # VPC DNS（Endpoint 需要，不影響 SSH）
    - name: Ensure VPC DNS support/hostnames enabled
      amazon.aws.ec2_vpc_net:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        dns_support: true
        dns_hostnames: true

    # ─────────────────────────────────────────────
    # IGW
    # ─────────────────────────────────────────────
    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-igw"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      when: subnets | selectattr('is_public','equalto',true) | list | length > 0
      register: igw_result

    - set_fact:
        igw_id: "{{ igw_result.gateway_id }}"
      when: igw_result.gateway_id is defined

    # ─────────────────────────────────────────────
    # Subnets
    # ─────────────────────────────────────────────
    - name: Create Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az | default(default_az) }}"
        map_public: "{{ item.is_public }}"
        state: present
        tags:
          Name: "{{ item.name }}"
          Project: "{{ project_name }}"
          SubnetName: "{{ item.name }}"
          Purpose: "{{ item.purpose }}"
          Type: "{{ 'Public' if item.is_public else 'Private' }}"
          Env: "{{ project_labels.env }}"
      loop: "{{ subnets }}"
      register: subnet_results

    - set_fact:
        public_subnet_ids: "{{ subnet_results.results
          | selectattr('subnet.map_public_ip_on_launch','equalto',true)
          | map(attribute='subnet.id') | list }}"

    - set_fact:
        private_subnet_ids: "{{ subnet_results.results
          | selectattr('subnet.map_public_ip_on_launch','equalto',false)
          | map(attribute='subnet.id') | list }}"

    # ─────────────────────────────────────────────
    # Route Tables
    # ─────────────────────────────────────────────
    - name: Create public route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ public_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-rt-public"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_id }}"
      when:
        - public_subnet_ids | length > 0
        - igw_id is defined

    - name: Create private route table (empty)
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-rt-private"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        routes: []
      when: private_subnet_ids | length > 0

    # ─────────────────────────────────────────────
    # NAT Gateway（完全保留你原本流程）
    # ─────────────────────────────────────────────
    - name: Lookup existing NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ cluster_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          state: available
          tag:Name: "{{ project_name }}-nat-gw"
      register: existing_nat
      when:
        - enable_nat_gateway
        - private_subnet_ids | length > 0

    - name: Use existing NAT Gateway if found
      set_fact:
        nat_gateway_id: "{{ existing_nat.result[0].nat_gateway_id }}"
      when:
        - enable_nat_gateway
        - existing_nat.result | default([]) | length > 0

    - name: Select public subnet for NAT Gateway
      set_fact:
        nat_public_subnet_id: "{{ public_subnet_ids[0] }}"
      when:
        - enable_nat_gateway
        - nat_gateway_id is not defined
        - public_subnet_ids | length > 0

    - name: Allocate Elastic IP for NAT Gateway
      amazon.aws.ec2_eip:
        region: "{{ cluster_region }}"
        in_vpc: true
        state: present
      register: nat_eip
      when:
        - enable_nat_gateway
        - nat_gateway_id is not defined

    - name: Create NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway:
        region: "{{ cluster_region }}"
        subnet_id: "{{ nat_public_subnet_id }}"
        allocation_id: "{{ nat_eip.allocation_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-nat-gw"
      register: nat_gw
      when:
        - enable_nat_gateway
        - nat_gateway_id is not defined

    - set_fact:
        nat_gateway_id: "{{ nat_gw.nat_gateway_id }}"
      when:
        - enable_nat_gateway
        - nat_gateway_id is not defined

    # ✅ 你有點名的：一定保留
    - name: Wait for NAT Gateway to become available
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ cluster_region }}"
        nat_gateway_ids:
          - "{{ nat_gateway_id }}"
      register: nat_gw_info
      until:
        - nat_gw_info.result is defined
        - nat_gw_info.result | length > 0
        - nat_gw_info.result[0].state == "available"
      retries: 15
      delay: 20
      changed_when: false
      when:
        - enable_nat_gateway
        - nat_gateway_id is defined

    - name: Attach NAT Gateway to private route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ nat_gateway_id }}"
      when:
        - enable_nat_gateway
        - nat_gateway_id is defined

    # ─────────────────────────────────────────────
    # Security Groups（完全回到你原本能用的版本）
    # ─────────────────────────────────────────────
    - name: Create Security Groups for each subnet
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ item.name | regex_replace('-subnet$', '-sg') }}"
        description: "Security Group for {{ item.name }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        rules: >
          {%- set base_rules = [{'proto': 'all', 'cidr_ip': vpc_cidr}] -%}
          {%- if enable_external_ssh and office_ip != '' -%}
            {{ base_rules + [{'proto': 'tcp', 'from_port': 22, 'to_port': 22, 'cidr_ip': office_ip}] }}
          {%- else -%}
            {{ base_rules }}
          {%- endif -%}
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      loop: "{{ subnets }}"

    # ─────────────────────────────────────────────
    # Key Pair（含 Expose）
    # ─────────────────────────────────────────────
    - name: Create key pair
      amazon.aws.ec2_key:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-keypair"
        state: present
      register: keypair_result

    - name: Expose SSH private key to frontend (FIRST TIME ONLY)
      set_stats:
        data:
          ssh_private_key_pem: "{{ keypair_result.key.private_key }}"
          ssh_keypair_name: "{{ keypair_result.key.name }}"
      when:
        - keypair_result.changed
        - keypair_result.key.private_key is defined

    # ─────────────────────────────────────────────
    # VPC Interface Endpoints（不影響 SSH）
    # ─────────────────────────────────────────────
    - name: Create VPC Endpoint SG
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-vpce-sg"
        vpc_id: "{{ vpc_id }}"
        state: present
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "{{ vpc_cidr }}"
      when:
        - private_subnet_ids | length > 0
        - enable_cloudwatch_endpoints or enable_ssm_endpoints

    - name: Create CloudWatch Endpoints
      amazon.aws.ec2_vpc_endpoint:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        service: "com.amazonaws.{{ cluster_region }}.{{ item }}"
        vpc_endpoint_type: Interface
        vpc_endpoint_subnets: "{{ private_subnet_ids }}"
        vpc_endpoint_security_groups:
          - "{{ project_name }}-vpce-sg"
        state: present
        tags:
          Name: "{{ project_name }}-vpce-{{ item }}"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      loop:
        - monitoring
        - logs
        - sts
      when:
        - enable_cloudwatch_endpoints
        - private_subnet_ids | length > 0

    # ─────────────────────────────────────────────
    # Summary
    # ─────────────────────────────────────────────
    - name: Summary
      debug:
        msg:
          - "VPC ID: {{ vpc_id }}"
          - "Public Subnets: {{ public_subnet_ids }}"
          - "Private Subnets: {{ private_subnet_ids }}"
          - "NAT Enabled: {{ enable_nat_gateway }}"
          - "NAT Gateway: {{ nat_gateway_id | default('N/A') }}"
          - "CloudWatch Endpoints Enabled: {{ enable_cloudwatch_endpoints }}"
          - "SSM Endpoints Enabled: {{ enable_ssm_endpoints }}"
