---
# Step 1: Create VPC / Subnets / Security Groups / Route Tables / SSH Key (+ NAT Gateway)
- name: Step 1 - Create VPC, Subnets, Security Groups, NAT Gateway
  hosts: localhost
  gather_facts: true
  collections:
    - amazon.aws

  vars:
    # ─────────────────────────────────────────────
    # 預設 Region / AZ
    # ─────────────────────────────────────────────
    default_cluster_region: ap-northeast-1
    cluster_region: "{{ cluster_region | default(default_cluster_region) }}"
    default_az: "{{ cluster_region }}a"

    # ─────────────────────────────────────────────
    # NAT Gateway 設定
    # ─────────────────────────────────────────────
    enable_nat_gateway: true

    # ─────────────────────────────────────────────
    # 外部 SSH 控制（測試/正式切換）
    # ─────────────────────────────────────────────
    enable_external_ssh: true
    office_ip: "{{ office_ip | default('') }}"

  tasks:

    # ─────────────────────────────────────────────
    # VPC
    # ─────────────────────────────────────────────
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}"
        cidr_block: "{{ vpc_cidr }}"
        state: present
        tags:
          Name: "{{ project_name }}"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ProjectId: "{{ project_labels['project.id'] }}"
          ManagedBy: Ansible
      register: vpc_result

    - name: Set VPC ID
      set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"

    # ─────────────────────────────────────────────
    # Internet Gateway (only if public subnet exists)
    # ─────────────────────────────────────────────
    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-igw"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      when: subnets | selectattr('is_public','equalto',true) | list | length > 0
      register: igw_result

    - name: Set IGW ID
      set_fact:
        igw_id: "{{ igw_result.gateway_id }}"
      when: igw_result.gateway_id is defined

    # ─────────────────────────────────────────────
    # Subnets
    # ─────────────────────────────────────────────
    - name: Create Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az | default(default_az) }}"
        map_public: "{{ item.is_public }}"
        state: present
        tags:
          Name: "{{ item.name }}"
          Project: "{{ project_name }}"
          SubnetName: "{{ item.name }}"
          Purpose: "{{ item.purpose }}"
          Type: "{{ 'Public' if item.is_public else 'Private' }}"
          Env: "{{ project_labels.env }}"
      loop: "{{ subnets }}"
      register: subnet_results

    - name: Get public subnets
      set_fact:
        public_subnet_ids: >-
          {{ subnet_results.results
             | selectattr('subnet.map_public_ip_on_launch','equalto',true)
             | map(attribute='subnet.id')
             | list }}

    - name: Get private subnets
      set_fact:
        private_subnet_ids: >-
          {{ subnet_results.results
             | selectattr('subnet.map_public_ip_on_launch','equalto',false)
             | map(attribute='subnet.id')
             | list }}

    # ─────────────────────────────────────────────
    # Public Route Table
    # ─────────────────────────────────────────────
    - name: Create public route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ public_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-rt-public"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_id }}"
      when:
        - public_subnet_ids | length > 0
        - igw_id is defined

    # ─────────────────────────────────────────────
    # NAT Gateway (for private subnets)
    # ─────────────────────────────────────────────
    - name: Select public subnet for NAT Gateway
      set_fact:
        nat_public_subnet_id: "{{ public_subnet_ids[0] }}"
      when:
        - enable_nat_gateway | bool
        - public_subnet_ids | length > 0

    - name: Allocate Elastic IP for NAT Gateway
      amazon.aws.ec2_eip:
        region: "{{ cluster_region }}"
        in_vpc: true
        state: present
        tags:
          Name: "{{ project_name }}-nat-eip"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      register: nat_eip
      when: enable_nat_gateway | bool

    - name: Create NAT Gateway
      amazon.aws.ec2_vpc_nat_gateway:
        region: "{{ cluster_region }}"
        subnet_id: "{{ nat_public_subnet_id }}"
        allocation_id: "{{ nat_eip.allocation_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-nat-gw"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
      register: nat_gw
      when: enable_nat_gateway | bool

    # ─────────────────────────────────────────────
    # Private Route Table (→ NAT Gateway)
    # ─────────────────────────────────────────────
    - name: Create private route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ cluster_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-rt-private"
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
        routes: >-
          {{
            enable_nat_gateway | bool
            | ternary(
                [{'dest': '0.0.0.0/0', 'nat_gateway_id': nat_gw.nat_gateway_id}],
                []
              )
          }}
      when: private_subnet_ids | length > 0

    # ─────────────────────────────────────────────
    # Security Groups (per subnet)
    # ─────────────────────────────────────────────
    - name: Create Security Groups for each subnet
      amazon.aws.ec2_security_group:
        region: "{{ cluster_region }}"
        name: "{{ item.name | regex_replace('-subnet$', '-sg') }}"
        description: "Security Group for {{ item.name }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ item.name | regex_replace('-subnet$', '-sg') }}"
          Project: "{{ project_name }}"
          SubnetName: "{{ item.name }}"
          Env: "{{ project_labels.env }}"
        rules: >-
          {% set base_rules = [{'proto': 'all', 'cidr_ip': vpc_cidr}] %}
          {% if enable_external_ssh | bool and office_ip | length > 0 %}
          {{ base_rules + [{'proto': 'tcp', 'from_port': 22, 'to_port': 22, 'cidr_ip': office_ip}] }}
          {% else %}
          {{ base_rules }}
          {% endif %}
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      loop: "{{ subnets }}"
      register: sg_results

    # ─────────────────────────────────────────────
    # Key Pair
    # ─────────────────────────────────────────────
    - name: Create key pair
      amazon.aws.ec2_key:
        region: "{{ cluster_region }}"
        name: "{{ project_name }}-keypair"
        state: present
        tags:
          Project: "{{ project_name }}"
          Env: "{{ project_labels.env }}"
          ManagedBy: Ansible
      register: keypair_result

    - name: Set key info
      set_fact:
        key_name: "{{ project_name }}-keypair"
        private_key_content: "{{ keypair_result.key.private_key | default('') }}"
        is_new_key: "{{ keypair_result.key.private_key is defined }}"

    # ─────────────────────────────────────────────
    # Summary
    # ─────────────────────────────────────────────
    - name: Summary
      debug:
        msg:
          - "══════════════════════════════════════════════════════"
          - "✅ VPC / Subnet / NAT Gateway 建立完成"
          - "══════════════════════════════════════════════════════"
          - "VPC ID: {{ vpc_id }}"
          - "Region: {{ cluster_region }}"
          - "Public Subnets: {{ public_subnet_ids | length }}"
          - "Private Subnets: {{ private_subnet_ids | length }}"
          - "NAT Gateway: {{ enable_nat_gateway }}"
          - "SSH Key: {{ key_name }}"
          - "══════════════════════════════════════════════════════"

    - name: Display SSH Private Key
      debug:
        msg:
          - "{{ private_key_content }}"
      when: is_new_key | bool
