---
# ════════════════════════════════════════════════════════════════
# AWS EC2 開機腳本
# ════════════════════════════════════════════════════════════════
# 使用場景: 啟動指定的 EC2 實例
# 
# 參數說明:
#   vpc_name: VPC 名稱 (用於識別和標記)
#   ec2_instance_id: EC2 實例 ID (例: i-0123456789abcdef0)
# ════════════════════════════════════════════════════════════════

- name: Power On AWS EC2 Instance
  hosts: localhost
  gather_facts: false
  
  vars:
    # ─────────────────────────────────────────────
    # 從前端/AWX 傳入的參數
    # ─────────────────────────────────────────────
    # vpc_name: "ita-vpc"                    # VPC 名稱
    # ec2_instance_id: "i-0123456789abcdef0" # EC2 實例 ID
    # aws_region: "ap-northeast-1"           # AWS Region (選填，預設 ap-northeast-1)
    
    # ─────────────────────────────────────────────
    # 預設值
    # ─────────────────────────────────────────────
    default_aws_region: ap-northeast-1
    aws_region: "{{ aws_region | default(default_aws_region) }}"

  tasks:
    # ─────────────────────────────────────────────
    # Task 1: 驗證參數
    # ─────────────────────────────────────────────
    - name: Set default region if not provided
      set_fact:
        aws_region: "{{ aws_region | default(default_aws_region) }}"
    
    - name: Validate required parameters
      fail:
        msg: "Missing required parameter: {{ item }}"
      when: vars[item] is not defined or vars[item] == ''
      loop:
        - vpc_name
        - ec2_instance_id

    # ─────────────────────────────────────────────
    # Task 2: 獲取 EC2 實例資訊
    # ─────────────────────────────────────────────
    - name: Get EC2 instance information
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        instance_ids:
          - "{{ ec2_instance_id }}"
      register: ec2_info

    # ─────────────────────────────────────────────
    # Task 3: 檢查實例是否存在
    # ─────────────────────────────────────────────
    - name: Check if instance exists
      fail:
        msg: "EC2 instance {{ ec2_instance_id }} not found"
      when: ec2_info.instances | length == 0

    # ─────────────────────────────────────────────
    # Task 4: 顯示當前實例狀態
    # ─────────────────────────────────────────────
    - name: Display current instance state
      debug:
        msg: "Current state of {{ ec2_instance_id }}: {{ ec2_info.instances[0].state.name }}"

    # ─────────────────────────────────────────────
    # Task 5: 啟動 EC2 實例
    # ─────────────────────────────────────────────
    - name: Start EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_ids:
          - "{{ ec2_instance_id }}"
        state: running
        wait: true
        wait_timeout: 300
      register: start_result
      when: ec2_info.instances[0].state.name != 'running'

    # ─────────────────────────────────────────────
    # Task 6: 顯示啟動結果
    # ─────────────────────────────────────────────
    - name: Display start result
      debug:
        msg: 
          - "EC2 Instance {{ ec2_instance_id }} has been started successfully"
          - "VPC: {{ vpc_name }}"
          - "Region: {{ aws_region }}"
      when: start_result is changed

    - name: Instance already running
      debug:
        msg: "EC2 Instance {{ ec2_instance_id }} is already in running state"
      when: ec2_info.instances[0].state.name == 'running'

    # ─────────────────────────────────────────────
    # Task 7: 獲取實例最新資訊 (包含 Public IP)
    # ─────────────────────────────────────────────
    - name: Get updated instance information
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        instance_ids:
          - "{{ ec2_instance_id }}"
      register: ec2_info_updated
      when: start_result is changed

    # ─────────────────────────────────────────────
    # Task 8: 記錄操作日誌
    # ─────────────────────────────────────────────
    - name: Log power on operation
      set_fact:
        operation_summary:
          action: "power_on"
          vpc_name: "{{ vpc_name }}"
          instance_id: "{{ ec2_instance_id }}"
          region: "{{ aws_region }}"
          previous_state: "{{ ec2_info.instances[0].state.name }}"
          final_state: "running"
          private_ip: "{{ ec2_info_updated.instances[0].private_ip_address | default('N/A') }}"
          public_ip: "{{ ec2_info_updated.instances[0].public_ip_address | default('N/A') }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
      when: start_result is changed

    - name: Log power on operation (already running)
      set_fact:
        operation_summary:
          action: "power_on"
          vpc_name: "{{ vpc_name }}"
          instance_id: "{{ ec2_instance_id }}"
          region: "{{ aws_region }}"
          previous_state: "{{ ec2_info.instances[0].state.name }}"
          final_state: "running"
          private_ip: "{{ ec2_info.instances[0].private_ip_address | default('N/A') }}"
          public_ip: "{{ ec2_info.instances[0].public_ip_address | default('N/A') }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
      when: ec2_info.instances[0].state.name == 'running'

    - name: Display operation summary
      debug:
        var: operation_summary
