---
# Step 1: Create VPC / Subnets / Security Groups / Route Tables / SSH Key

- name: Step 1 - Create VPC, Subnets, Security Groups
  hosts: localhost
  gather_facts: true
  collections:
    - amazon.aws
    - community.aws

  vars:
    aws_region: ap-northeast-1
    default_az: "{{ aws_region }}a"
    office_ip: "203.0.113.10/32"

  tasks:

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        region: "{{ aws_region }}"
        name: "{{ project_name }}-VPC"
        cidr_block: "{{ vpc_cidr }}"
        state: present
        tags:
          Name: "{{ project_name }}-VPC"
          Project: "{{ project_name }}"
          ManagedBy: Ansible
      register: vpc_result

    - name: Set VPC ID
      set_fact:
        vpc_id: "{{ vpc_result.vpc.id }}"

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-IGW"
          Project: "{{ project_name }}"
      when: subnets | selectattr('is_public','equalto',true) | list | length > 0
      register: igw_result

    - name: Set IGW ID
      set_fact:
        igw_id: "{{ igw_result.gateway_id }}"
      when: igw_result.gateway_id is defined

    - name: Create Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az | default(default_az) }}"
        map_public: "{{ item.is_public }}"
        state: present
        tags:
          Name: "{{ project_name }}-{{ item.name }}-subnet"
          Project: "{{ project_name }}"
          Subnet: "{{ item.name }}"
          Purpose: "{{ item.purpose }}"
          Type: "{{ 'Public' if item.is_public else 'Private' }}"
      loop: "{{ subnets }}"
      register: subnet_results

    - name: Get public subnets
      set_fact:
        public_subnet_ids: "{{ subnet_results.results |
                               selectattr('subnet.map_public_ip_on_launch','equalto',true) |
                               map(attribute='subnet.id') | list }}"

    - name: Create public route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ public_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-RT-Public"
          Project: "{{ project_name }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_id }}"
      when:
        - public_subnet_ids | length > 0
        - igw_id is defined

    - name: Get private subnets
      set_fact:
        private_subnet_ids: "{{ subnet_results.results |
                                selectattr('subnet.map_public_ip_on_launch','equalto',false) |
                                map(attribute='subnet.id') | list }}"

    - name: Create private route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        state: present
        subnets: "{{ private_subnet_ids }}"
        tags:
          Name: "{{ project_name }}-RT-Private"
          Project: "{{ project_name }}"
        routes: []
      when: private_subnet_ids | length > 0

    - name: Create Security Groups for each subnet
      amazon.aws.ec2_security_group:
        region: "{{ aws_region }}"
        name: "{{ project_name }}-{{ item.name }}-sg"
        description: "Security Group for {{ item.name }} subnet"
        vpc_id: "{{ vpc_id }}"
        state: present
        tags:
          Name: "{{ project_name }}-{{ item.name }}-sg"
          Project: "{{ project_name }}"
          Subnet: "{{ item.name }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ office_ip }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      loop: "{{ subnets }}"
      register: sg_results

    - name: Create key pair
      amazon.aws.ec2_key:
        region: "{{ aws_region }}"
        name: "{{ project_name }}-keypair"
        state: present
      register: keypair_result

    - name: Set key info
      set_fact:
        key_name: "{{ project_name }}-keypair"
        private_key_content: "{{ keypair_result.key.private_key | default('') }}"
        is_new_key: "{{ keypair_result.key.private_key is defined }}"

    - name: Store private key to Secrets Manager
      community.aws.secretsmanager_secret:
        name: "{{ project_name }}/ssh-keypair"
        state: present
        secret_type: 'string'
        secret: "{{ private_key_content }}"
        description: "SSH private key for {{ project_name }}"
        region: "{{ aws_region }}"
        tags:
          Project: "{{ project_name }}"
          ManagedBy: "Ansible"
      when: is_new_key | bool
      ignore_errors: yes

    - name: Summary
      debug:
        msg:
          - "VPC: {{ vpc_id }}"
          - "Subnets: {{ subnets | length }}"
          - "Security Groups: {{ sg_results.results | length }}"
          - "SSH Key: {{ key_name }}"
          - "Saved To Secrets Manager: {{ project_name }}/ssh-keypair (if new)"
